<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class accountData extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('account_data')->truncate();
        DB::table('account_data')->insert([
            [
                'id' => '1',
                'code' => '110101011',
                'name' => 'Kas Kecil Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'active' => 'Y',
                'account_type' => '-',
                'debet_kredit' => 'D',
                'main_id' => '1',
                'main_detail_id' => '1',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '2',
                'code' => '110101012',
                'name' => 'Kas Kecil Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'active' => 'Y',
                'account_type' => '-',
                'debet_kredit' => 'D',
                'main_id' => '1',
                'main_detail_id' => '1',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '3',
                'code' => '410101011',
                'name' => 'Pendapatan Jasa Service Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'active' => 'Y',
                'account_type' => '-',
                'debet_kredit' => 'D',
                'main_id' => '5',
                'main_detail_id' => '5',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '4',
                'code' => '410101012',
                'name' => 'Pendapatan Jasa Service Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '5',
                'main_detail_id' => '5',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '5',
                'code' => '410201011',
                'name' => 'Pendapatan Barang Service Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'active' => 'Y',
                'account_type' => '-',
                'debet_kredit' => 'D',
                'main_id' => '5',
                'main_detail_id' => '6',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '6',
                'code' => '410201012',
                'name' => 'Pendapatan Barang Service Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '5',
                'main_detail_id' => '6',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '7',
                'code' => '140101011',
                'name' => 'Pendapatan Dimuka Service Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '4',
                'main_detail_id' => '4',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '8',
                'code' => '140101012',
                'name' => 'Pendapatan Dimuka Service Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '4',
                'main_detail_id' => '4',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '9',
                'code' => '110301011',
                'name' => 'Kas Bank Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '1',
                'main_detail_id' => '3',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '10',
                'code' => '110301012',
                'name' => 'Kas Bank Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '1',
                'main_detail_id' => '3',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '11',
                'code' => '510101011',
                'name' => 'Return Service Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '7',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '12',
                'code' => '510101012',
                'name' => 'Return Service Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '7',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '13',
                'code' => '510401011',
                'name' => 'Biaya Listrik Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '10',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '14',
                'code' => '130101011',
                'name' => 'Persediaan Barang Dagang Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '3',
                'main_detail_id' => '11',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '15',
                'code' => '130101012',
                'name' => 'Persediaan Barang Dagang Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '3',
                'main_detail_id' => '11',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '16',
                'code' => '140201011',
                'name' => 'Pembayaran Dimuka Pembelian Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '4',
                'main_detail_id' => '12',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '17',
                'code' => '140201012',
                'name' => 'Pembayaran Dimuka Pembelian Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '4',
                'main_detail_id' => '12',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '18',
                'code' => '510501011',
                'name' => 'Pembayaran Air (PDAM) Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '13',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '19',
                'code' => '500101011',
                'name' => 'Sharing Profit Sharing Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '14',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '20',
                'code' => '500201011',
                'name' => 'Gaji (Fee Back Office) Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '15',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '21',
                'code' => '510401012',
                'name' => 'Biaya Listrik Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '10',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '22',
                'code' => '500101012',
                'name' => 'Sharing Profit Sharing Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '14',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '23',
                'code' => '510501012',
                'name' => 'Pembayaran Air (PDAM) Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '13',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '24',
                'code' => '500201012',
                'name' => 'Gaji (Fee Back Office) Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '15',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '25',
                'code' => '510201011',
                'name' => 'Return Penjualan Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '8',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '26',
                'code' => '510201012',
                'name' => 'Return Penjualan Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '8',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '27',
                'code' => '510301011',
                'name' => 'Biaya Operasional Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '9',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '28',
                'code' => '510301012',
                'name' => 'Biaya Operasional Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '9',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '29',
                'code' => '500301012',
                'name' => 'Biaya Sewa Ruko Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '16',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '30',
                'code' => '500301011',
                'name' => 'Biaya Sewa Ruko Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '16',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '31',
                'code' => '500401011',
                'name' => 'Biaya Sewa Hosting & Domain Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '17',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '32',
                'code' => '500401012',
                'name' => 'Biaya Sewa Hosting & Domain Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '17',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '33',
                'code' => '500501012',
                'name' => 'THR (Tunjangan Hari Raya) Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '18',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '34',
                'code' => '500501011',
                'name' => 'THR (Tunjangan Hari Raya) Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '18',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '35',
                'code' => '510601011',
                'name' => 'Biaya Meeting / Konsumsi Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '19',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '36',
                'code' => '510601012',
                'name' => 'Biaya Meeting / Konsumsi Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '19',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '37',
                'code' => '510701012',
                'name' => 'Biaya Internet Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '20',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '38',
                'code' => '510701011',
                'name' => 'Biaya Internet Cabang Jenggolo',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '20',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '39',
                'code' => '511001012',
                'name' => 'Biaya Sosial Internal Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '23',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '40',
                'code' => '511001011',
                'name' => 'Biaya Sosial Internal Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '23',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '41',
                'code' => '511101011',
                'name' => 'Biaya Wisata Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '24',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '42',
                'code' => '511101012',
                'name' => 'Biaya Wisata Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '24',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '43',
                'code' => '511201012',
                'name' => 'Biaya Qurban Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '25',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '44',
                'code' => '511201011',
                'name' => 'Biaya Qurban Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '25',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '45',
                'code' => '511301011',
                'name' => 'Biaya ATK Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '26',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '46',
                'code' => '511301012',
                'name' => 'Biaya ATK Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '6',
                'main_detail_id' => '26',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '47',
                'code' => '410301011',
                'name' => 'Pendapatan Barang Dagang Cabang Pusat',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '5',
                'main_detail_id' => '27',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '48',
                'code' => '410301012',
                'name' => 'Pendapatan Barang Dagang Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '5',
                'main_detail_id' => '27',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '49',
                'code' => '500601012',
                'name' => 'Transfer /  Setoran',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '28',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '50',
                'code' => '500601011',
                'name' => 'Transfer',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'K',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '28',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '51',
                'code' => '500701011',
                'name' => 'Biaya HPP Cabang Jenggolo',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '29',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '52',
                'code' => '500701012',
                'name' => 'Biaya HPP Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '7',
                'main_detail_id' => '29',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '53',
                'code' => '420201011',
                'name' => 'Diskon Service Cabang Jenggolo',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '8',
                'main_detail_id' => '31',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '54',
                'code' => '420201012',
                'name' => 'Diskon Service Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '8',
                'main_detail_id' => '31',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '55',
                'code' => '420101011',
                'name' => 'Diskon Penjualan Cabang Jenggolo',
                'area_id' => '1',
                'branch_id' => '1',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '8',
                'main_detail_id' => '30',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
            [
                'id' => '56',
                'code' => '420101012',
                'name' => 'Diskon Penjualan Cabang Mukmin',
                'area_id' => '1',
                'branch_id' => '2',
                'debet_kredit' => 'D',
                'active' => 'Y',
                'account_type' => '-',
                'main_id' => '8',
                'main_detail_id' => '30',
                'opening_balance' => 0,
                'opening_date' => date('Y-m-d'),
                'created_at' => date("Y-m-d h:i:s"),
                'updated_at' => date("Y-m-d h:i:s"),
            ],
        ]);
    }
}
